#!/usr/bin/env python
"""Task 3a: write docs/gate_spec.md from the code itself, so the specification cannot drift.

Pre-registered in RESEARCH_LOG.md (2026-09-14, "Task 3 pre-registration").  Everything below is
read from the modules the benchmark runs: the feature registry, the line of code that registers each
feature, the model factory, and the functions that fit and time the gates.
"""
from __future__ import annotations

import importlib.util, inspect, json, re, sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from rap import features as F, geometry as G, predict                          # noqa: E402
from rap.cache import DetCache                                                  # noqa: E402
from rap.paths import CACHE, RESULTS                                            # noqa: E402
from rap.risk import RiskConfig                                                 # noqa: E402
from rap.tables import feature_columns                                          # noqa: E402


def _load(name, file):
    s = importlib.util.spec_from_file_location(name, ROOT / "scripts" / file)
    m = importlib.util.module_from_spec(s)
    s.loader.exec_module(m)
    return m


def registration_lines():
    """feature name -> the source line that computes and registers it."""
    src = (ROOT / "src" / "rap" / "features.py").read_text().splitlines()
    out = {}
    for i, line in enumerate(src, 1):
        for m in re.finditer(r'_reg\("([a-z0-9_]+)"', line):
            out[m.group(1)] = (i, line.strip())
    return out


def main():
    cfg = RiskConfig()
    c = DetCache(CACHE / "nusc_det_tv" / "ns_cheap_320" / "scene-0001.npz")
    sc = c.scalars(0)
    img = {k: v for k, v in sc.items() if k.startswith(("img_bright", "img_dark", "img_lap", "img_edge", "img_contrast", "motion"))}
    rec = F.frame_features(c.det(0), c.geo(0), img, sc.get("img_w", 1600.0) * sc.get("img_h", 900.0), G.PRIMARY, cfg.op_conf)
    import pandas as pd
    cols = feature_columns(pd.DataFrame([rec]))            # the order and the leakage guard the gates use
    reg = F.registry()
    lines = registration_lines()
    t92 = _load("t92", "92_benchmark_table.py")
    g84 = _load("g84", "84_deployable_gate.py")
    nuplan = json.loads((Path(RESULTS) / "final" / "benchmark_nuplan_signals.json").read_text())
    nsrc = (ROOT / "scripts" / "91_nuplan_cheap_features.py").read_text().splitlines()

    md = ["# Gate specification (generated by `scripts/105_gate_spec.py` — do not edit by hand)", "",
          "Everything here is read from the code the benchmark runs. Feature definitions are the exact",
          "source line that computes and registers each feature in `src/rap/features.py`; `source` is the",
          "provenance label `assert_no_leakage` checks (only cheap-side sources are legal for a gate).", "",
          f"## 1. The {len(cols)} cheap-side features (nuScenes and KITTI), in model column order", "",
          "Built per frame by `rap.features.frame_features(det, geo, img_stats, img_area, G.PRIMARY, op_conf=0.25)`",
          "from the CHEAP detector cache only: detections, their monocular geometry `mono.predicted_geometry`",
          "(boxes, calibration, previous CHEAP frame) and image statistics of the downscaled CHEAP input.", "",
          "| # | feature | group | source | defining line (features.py) |", "|---|---|---|---|---|"]
    for i, name in enumerate(cols, 1):
        g, s = reg[name]
        ln, txt = lines.get(name, (None, ""))
        txt = txt.replace("|", "\\|")
        md.append(f"| {i} | `{name}` | {g} | {s} | L{ln}: `{txt}` |")
    groups = {}
    for name in cols:
        groups.setdefault(reg[name][0], 0)
        groups[reg[name][0]] += 1
    md += ["", "Features per group: " + ", ".join(f"{k} {v}" for k, v in groups.items()) + ".", "",
           "Missing values (a frame with no detections) are filled with 0 before fitting; infinities are clipped",
           "to ±1e6 (`np.nan_to_num(..., nan=0.0, posinf=1e6, neginf=-1e6)`).", "",
           f"## 2. The {len(nuplan['gate_features'])} nuPlan gate features", "",
           "Computed by `scripts/91_nuplan_cheap_features.py` at the decision iteration from the tracks the CHEAP",
           "branch kept (plus the previous iteration's CHEAP tracks, ego state and traffic-light status).",
           f"Excluded from the gate: privileged {nuplan['privileged']} and diagnostic {nuplan['diagnostic']}.", "",
           "| # | feature | defining line (91_nuplan_cheap_features.py) |", "|---|---|---|"]
    for i, name in enumerate(nuplan["gate_features"], 1):
        hit = next(((k, l.strip()) for k, l in enumerate(nsrc, 1)
                    if re.search(rf'r\["{name}"\]\s*=|r\[f"n_cheap_fov_{{c}}"\]' if name.startswith("n_cheap_fov_") else rf'"{name}"\s*:|r\["{name}"\]\s*=', l)), (None, ""))
        md.append(f"| {i} | `{name}` | L{hit[0]}: `{hit[1].replace('|', chr(92) + '|')}` |")

    lin = predict.make_model("linear", "reg", 0)
    gbm = predict.make_model("gbm", "reg", 0)
    md += ["", "## 3. Models and hyperparameters (`rap.predict.make_model`, task = regression, seed 0)", "",
           "**gate ridge** — `Pipeline([StandardScaler(), RidgeCV(alphas=logspace(-2, 4, 13))])`; alpha chosen by",
           "RidgeCV's efficient leave-one-out CV on the training rows only.", "",
           "```", json.dumps({k: (v.tolist() if isinstance(v, np.ndarray) else v) for k, v in lin.named_steps["m"].get_params().items()}, indent=1, default=str), "```", "",
           "**gate GBM** — `HistGradientBoostingRegressor`, fixed configuration, no tuning:", "",
           "```", json.dumps(gbm.get_params(), indent=1, default=str), "```", "",
           "Target: V = J_CHEAP − J_FULL of the cell's downstream system (regression on the raw value);",
           "the score used for allocation is the prediction.", "",
           "## 4. Training procedures", "",
           "**Development (leave-one-scene-out), `84_deployable_gate.py`** — `rap.predict.loso`: one fold per",
           "sequence/scene, the model refit on all other units and predicting the held-out unit; folds run in",
           "parallel single-threaded workers; `assert_no_leakage` runs on the column list first.", "",
           "```python", inspect.getsource(predict.loso).rstrip(), "```", "",
           "**Benchmark (frozen split), `92_benchmark_table.py`** — fit once on train ∪ val units of",
           "`configs/benchmark_splits.json`, predict every frame, score test frames only:", "",
           "```python", inspect.getsource(t92.gate_predictions).rstrip(), "```", "",
           "**Feature construction for the benchmark**, `84_deployable_gate.build_features`:", "",
           "```python", inspect.getsource(g84.build_features).rstrip(), "```", "",
           "**Cost charged under measured budgets**, `93_budget_allocation.py`: single-frame median latency of",
           "`frame_features` (3.6 ms nuScenes, 3.9 ms KITTI) plus single-row `predict` (ridge 0.39 ms, GBM",
           "16.1 ms; 12.9 ms with one OpenMP thread), CPU-rail power over idle while running; batched GBM",
           "inference amortises to 0.021 ms per frame (`benchmark_gate_inference_batch_timing.json`).", ""]
    out = ROOT / "docs" / "gate_spec.md"
    out.write_text("\n".join(md))
    print(f"wrote {out}: {len(cols)} features ({groups}), {len(nuplan['gate_features'])} nuPlan features")


if __name__ == "__main__":
    main()
