#!/usr/bin/env python
"""Task 3b: what a real-perception nuPlan run would need -- estimate only, nothing is downloaded.

Pre-registered in RESEARCH_LOG.md (2026-09-14, "Task 3 pre-registration").  Reads the local nuPlan
mini log databases with the standard-library sqlite3 module (read-only), counts front-camera images
for the 34 benchmark logs and the 9 test logs, and turns the counts into disk and runtime estimates.
Every number that is an estimate rather than a count is labelled as such in the output.
"""
from __future__ import annotations

import json, os, shutil, sqlite3
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DB_DIR = Path("/home/kongwoang/datasets/nuplan/nuplan-v1.1/splits/mini")
NUSC_JPG_KB, NUSC_PIX = 146.9, 1600 * 900          # measured mean of the 3,376 local CAM_FRONT JPEGs
NUSC_DET_S, NUSC_DET_FRAMES = 208.0, 3376          # logs/nusc_detect_tv.log: two modes, decode included
HISTORY_S = 2.0                                    # history kept before each scenario window


def main():
    splits = json.loads((ROOT / "configs" / "benchmark_splits.json").read_text())["nuplan"]
    meta = pd.read_csv(ROOT / "configs" / "benchmark_nuplan_scenarios.csv")
    logs_all = sorted(splits["train"] + splits["val"] + splits["test"])
    logs_test = sorted(splits["test"])
    rows = []
    for log in logs_all:
        con = sqlite3.connect(f"file:{DB_DIR / (log + '.db')}?mode=ro", uri=True)
        cam = con.execute("select token, width, height from camera where channel='CAM_F0'").fetchone()
        ts = [r[0] for r in con.execute("select timestamp from image where camera_token=? order by timestamp", (cam[0],))]
        path = con.execute("select filename_jpg from image where camera_token=? limit 1", (cam[0],)).fetchone()[0]
        sc = meta[meta.log == log]
        inwin = set()
        for _, s in sc.iterrows():
            lo, hi = (s.t0 - HISTORY_S) * 1e6, s.t1 * 1e6
            inwin.update(i for i, t in enumerate(ts) if lo <= t <= hi)
        con.close()
        rows.append({"log": log, "split": next(k for k in ("train", "val", "test") if log in splits[k]),
                     "n_scenarios": len(sc), "cam_f0_width": cam[1], "cam_f0_height": cam[2],
                     "cam_f0_images_log": len(ts), "cam_f0_images_scenario_windows": len(inwin),
                     "log_duration_s": (ts[-1] - ts[0]) / 1e6 if ts else 0.0,
                     "example_blob_path": path})
    d = pd.DataFrame(rows)
    pix = float((d.cam_f0_width * d.cam_f0_height).iloc[0])
    kb = NUSC_JPG_KB * pix / NUSC_PIX
    ms_per_frame = 1e3 * NUSC_DET_S / NUSC_DET_FRAMES * pix / NUSC_PIX
    free_gb = shutil.disk_usage("/home/kongwoang").free / 1e9

    def summarise(sub, label):
        n_log, n_win = int(sub.cam_f0_images_log.sum()), int(sub.cam_f0_images_scenario_windows.sum())
        return {"set": label, "logs": len(sub), "scenarios": int(sub.n_scenarios.sum()),
                "cam_f0_images_whole_logs": n_log, "cam_f0_images_scenario_windows": n_win,
                "est_gb_whole_logs": n_log * kb / 1e6, "est_gb_scenario_windows": n_win * kb / 1e6,
                "est_detector_hours_whole_logs": n_log * ms_per_frame / 3.6e6,
                "est_detector_hours_scenario_windows": n_win * ms_per_frame / 3.6e6}

    summ = pd.DataFrame([summarise(d, "34 benchmark logs"), summarise(d[d.split == "test"], "9 test logs")])
    test = summ.iloc[1]
    feasible = bool(test.est_gb_scenario_windows <= 0.25 * free_gb and test.est_detector_hours_scenario_windows < 2.0)

    out = ROOT / "results" / "final"
    d.to_csv(out / "nuplan_camera_feasibility_logs.csv", index=False)
    summ.to_csv(out / "nuplan_camera_feasibility_summary.csv", index=False)
    md = ["# Real-perception nuPlan run: feasibility (estimate only — nothing downloaded)", "",
          "Generated by `scripts/106_nuplan_feasibility.py` from the local nuPlan **mini** log databases",
          "(read-only sqlite). Pre-registered in RESEARCH_LOG.md (2026-09-14, Task 3).", "",
          "## What is counted (exact)", "",
          f"* Front camera `CAM_F0`, {int(d.cam_f0_width.iloc[0])} × {int(d.cam_f0_height.iloc[0])} px, "
          f"{d.cam_f0_images_log.sum() / d.log_duration_s.sum():.1f} images per second of log.",
          f"* Scenario windows: each benchmark scenario's [t0 − {HISTORY_S:.0f} s, t1], the {HISTORY_S:.0f} s covering the planner's history buffer.",
          f"* Blob paths are relative to the sensor root, e.g. `{d.example_blob_path.iloc[0]}`.", "",
          "| set | logs | scenarios | CAM_F0 images, whole logs | CAM_F0 images, scenario windows |", "|---|---|---|---|---|"]
    for _, r in summ.iterrows():
        md.append(f"| {r['set']} | {r.logs} | {r.scenarios} | {r.cam_f0_images_whole_logs:,} | {r.cam_f0_images_scenario_windows:,} |")
    md += ["", "## What is estimated", "",
           f"* **JPEG size ≈ {kb:.0f} KB per image** — no nuPlan image exists locally, so this is the measured mean of the",
           f"  local nuScenes CAM_FRONT JPEGs ({NUSC_JPG_KB} KB at 1600 × 900) scaled by pixel count. Real compression may differ.",
           f"* **Detector runtime ≈ {ms_per_frame:.0f} ms per image for CHEAP + FULL** — the logged nuScenes run (3,376 frames, two",
           f"  YOLOv8s modes, JPEG decode included, {NUSC_DET_S:.0f} s) scaled by pixel count.",
           f"* Free disk now: **{free_gb:.0f} GB**.", "",
           "| set | est. GB, whole logs | est. GB, windows | est. detector h, whole logs | est. detector h, windows |", "|---|---|---|---|---|"]
    for _, r in summ.iterrows():
        md.append(f"| {r['set']} | {r.est_gb_whole_logs:.1f} | {r.est_gb_scenario_windows:.2f} | "
                  f"{r.est_detector_hours_whole_logs:.2f} | {r.est_detector_hours_scenario_windows:.2f} |")
    md += ["", "## What cannot be determined offline", "",
           "* **Which distribution archives hold these logs.** nuPlan ships sensor blobs as multi-GB archives that bundle",
           "  many logs and all eight cameras; there is no archive index on this disk, so the archive list, and therefore",
           "  the real download size (all cameras, not only CAM_F0), is unknown until an index is fetched.",
           "* Actual JPEG sizes, and whether the mini-split blobs are published per log.", "",
           "## Reading (pre-registered)", "",
           f"\"Feasible now\" requires the scenario-window images of the 9 test logs to fit in 25% of free disk "
           f"({0.25 * free_gb:.0f} GB) and the scaled detector runtime to stay under 2 h: "
           f"{test.est_gb_scenario_windows:.2f} GB and {test.est_detector_hours_scenario_windows:.2f} h → "
           f"**{'feasible' if feasible else 'not feasible'}** on those two criteria. The binding unknown is the archive",
           "granularity: if only whole multi-camera archives are available, the download is far larger than the",
           "CAM_F0 estimate above.", "", "## Per log", "",
           "| log | split | scenarios | CAM_F0 images (log) | images (windows) |", "|---|---|---|---|---|"]
    for _, r in d.iterrows():
        md.append(f"| {r.log} | {r.split} | {r.n_scenarios} | {r.cam_f0_images_log:,} | {r.cam_f0_images_scenario_windows:,} |")
    (ROOT / "docs" / "nuplan_real_perception_feasibility.md").write_text("\n".join(md) + "\n")
    print(summ.round(2).to_string(index=False))
    print(f"free {free_gb:.0f} GB, est {kb:.0f} KB/image, {ms_per_frame:.0f} ms/image -> feasible={feasible}")


if __name__ == "__main__":
    main()
