#!/usr/bin/env python
"""Render the Task 1 calibration CSVs as markdown, so no number in docs/iclr_calibration.md is copied by hand.

Reads results/final/calibration_{thresholds,cells,sweep,brake_vs_plan}.csv, calibration_reading.json
and calibration_pr_curves.csv; writes docs/calibration_tables.md.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FINAL = ROOT / "results" / "final"
SCHEMES = ("S0", "S1", "S2", "S3", "S4")
GAINS = ("exact_FN", "FN_FP", "E5_combined", "E_risk")


def pct(x):
    return "—" if x is None or not np.isfinite(x) else f"{100 * x:.1f}%"


def f2(x):
    return "—" if x is None or not np.isfinite(x) else f"{x:.2f}"


def main():
    th = pd.read_csv(FINAL / "calibration_thresholds.csv")
    c = pd.read_csv(FINAL / "calibration_cells.csv")
    sw = pd.read_csv(FINAL / "calibration_sweep.csv")
    bp = pd.read_csv(FINAL / "calibration_brake_vs_plan.csv")
    reading = json.loads((FINAL / "calibration_reading.json").read_text())
    cells = list(dict.fromkeys(c.cell))
    md = ["# Calibration tables (generated by scripts/109_calibration_markdown.py — do not edit by hand)", "",
          "Harm rate = P(V<0 | V≠0); ρ = Σ max(−V,0) / Σ max(V,0). Brackets: unit-bootstrap 95% CI "
          "(scene / sequence, 1000 draws). Thresholds are (CHEAP, FULL), chosen on train ∪ val only.", ""]

    md += ["## Pre-registered reading (all units)", "", "| scheme | nuScenes cells passing (≥3 of 4) | "
           "KITTI moderate-gap cells passing (6 of 6) | cells below the collapse line | survives | collapses |",
           "|---|---|---|---|---|---|"]
    for s in ("S1", "S2", "S3"):
        r = reading[s]
        md.append(f"| {s} | {r['nuScenes_cells_passing']} | {r['kitti_moderate_cells_passing']} | "
                  f"{r['cells_below_collapse_line']} of {r['n_cells']} | {r['survives']} | {r['collapses']} |")
    md += ["", f"**Verdict: {reading['verdict']}**", ""]

    md += ["## Chosen thresholds (CHEAP / FULL)", "", "| cell | " + " | ".join(SCHEMES) + " |",
           "|" + "---|" * (len(SCHEMES) + 1)]
    for cell in cells:
        t = th[th.cell == cell].set_index("scheme")
        md.append(f"| {cell} | " + " | ".join(
            f"{t.loc[s, 't_cheap']:.2f} / {t.loc[s, 't_full']:.3f}" + (" †" if bool(t.loc[s, "S4_tie"]) else "")
            for s in SCHEMES) + " |")
    md += ["", "† S4 tie broken toward 0.25.", ""]

    for split in ("all", "test"):
        md += [f"## Harm rate and ρ per scheme — {split} units", "",
               "| cell | " + " | ".join(f"{s} harm | {s} ρ" for s in SCHEMES) + " |",
               "|" + "---|" * (2 * len(SCHEMES) + 1)]
        for cell in cells:
            x = c[(c.cell == cell) & (c.split == split)].set_index("scheme")
            vals = []
            for s in SCHEMES:
                r = x.loc[s]
                vals.append(f"{pct(r.harm_rate)} [{pct(r.harm_rate_lo)}, {pct(r.harm_rate_hi)}]")
                vals.append(f"{f2(r.rho)} [{f2(r.rho_lo)}, {f2(r.rho_hi)}]")
            md.append(f"| {cell} | " + " | ".join(vals) + " |")
        md.append("")

    for split in ("all", "test"):
        md += [f"## Affected frames, all-FULL and oracle@20 loss reduction, detector operating points — {split} units", "",
               "| cell | scheme | affected / frames | harmed | all-FULL | oracle@20 | CHEAP det/frame · P · R | FULL det/frame · P · R |",
               "|---|---|---|---|---|---|---|---|"]
        for cell in cells:
            for s in SCHEMES:
                r = c[(c.cell == cell) & (c.split == split) & (c.scheme == s)].iloc[0]
                md.append(f"| {cell} | {s} | {r.affected} / {r.n_frames} | {r.harmed} | {pct(r.all_full_reduction)} | "
                          f"{pct(r.oracle20_reduction)} | {r.cheap_det_per_frame:.2f} · {r.cheap_precision:.3f} · "
                          f"{r.cheap_recall:.3f} | {r.full_det_per_frame:.2f} · {r.full_precision:.3f} · {r.full_recall:.3f} |")
        md.append("")

    nus = c[c.dataset == "nuScenes"]
    for split in ("all", "test"):
        md += [f"## nuScenes sign agreement between perception gains and V — {split} units", "",
               "Sign disagreement: share of frames with gain ≠ 0 and V ≠ 0 whose signs differ. Spearman: over all frames. "
               "Harmed | gain>0: P(V<0 | gain>0); in brackets, the same among affected frames.", "",
               "| cell | scheme | " + " | ".join(f"{g}: disagree · ρ_s · harmed|gain>0" for g in GAINS) + " |",
               "|" + "---|" * (len(GAINS) + 2)]
        for cell in [x for x in cells if x.startswith("nuScenes")]:
            for s in SCHEMES:
                r = nus[(nus.cell == cell) & (nus.split == split) & (nus.scheme == s)].iloc[0]
                md.append(f"| {cell} | {s} | " + " | ".join(
                    f"{pct(r[f'{g}_sign_disagreement'])} · {r[f'{g}_spearman']:+.3f} · {pct(r[f'{g}_harmed_given_gain_pos'])} "
                    f"({pct(r[f'{g}_harmed_given_gain_pos_affected'])})" for g in GAINS) + " |")
        md.append("")

    md += ["## nuScenes braking controller vs PKL's planner: opposite-sign frames", "",
           "| geometry | scheme | split | plan frames | both V ≠ 0 | opposite sign |", "|---|---|---|---|---|---|"]
    for _, r in bp.iterrows():
        md.append(f"| {r.geometry} | {r.scheme} | {r.split} | {r.n_plan_frames} | {r.both_nonzero} | {r.opposite_sign} |")
    md.append("")

    grid = sorted(sw.t_cheap.unique())
    md += ["## Sensitivity sweep, all units: harm rate / ρ over (CHEAP, FULL) thresholds", ""]
    for cell in cells:
        x = sw[sw.cell == cell]
        md += [f"**{cell}** — rows CHEAP threshold, columns FULL threshold", "",
               "| CHEAP \\ FULL | " + " | ".join(f"{t:.2f}" for t in grid) + " |", "|" + "---|" * (len(grid) + 1)]
        for tc in grid:
            row = []
            for tf in grid:
                r = x[(np.isclose(x.t_cheap, tc)) & (np.isclose(x.t_full, tf))].iloc[0]
                row.append(f"{pct(r.harm_rate)} / {f2(r.rho)}")
            md.append(f"| {tc:.2f} | " + " | ".join(row) + " |")
        md.append("")

    out = ROOT / "docs" / "calibration_tables.md"
    out.write_text("\n".join(md))
    print("wrote", out)


if __name__ == "__main__":
    main()
