#!/usr/bin/env python
"""Render the Task 2 router CSVs as markdown, so no number in docs/iclr_routers.md is copied by hand.

Reads results/final/benchmark_table_routers.csv, benchmark_table.csv (the 65-feature gates, same test
split), benchmark_budget_routers.csv, benchmark_budget_overheads_routers.json and the R2 meta files;
writes docs/routers_tables.md.
"""
from __future__ import annotations

import glob, json
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FINAL = ROOT / "results" / "final"
KEY = ["track", "geometry", "system", "target"]
ROUTERS = ["R1_mlp_reg", "R1_mlp_clf", "R1_gbm_reg", "R1_gbm_clf", "R2_cnn_clf"]
GATES = ["gate_ridge", "gate_gbm"]
BUDGET_SIGNALS = ["random", "uncertainty", "gate_ridge", "gate_gbm", "gate_gbm_batched"] + ROUTERS


def read(name):
    d = pd.read_csv(FINAL / name)
    if "geometry" in d:
        d["geometry"] = d.geometry.fillna("n/a")
    d["cell"] = d.track + " · " + d.geometry.replace("n/a", "") + " · " + d.system + " · " + d.target
    d["cell"] = d.cell.str.replace(" ·  · ", " · ")
    return d


def fmt(r):
    if r is None:
        return "—"
    s = f"{r.eta:+.2f}"
    return f"**{s}**" if np.isfinite(r.minus_random_lo) and r.minus_random_lo > 0 else s


def main():
    rt = read("benchmark_table_routers.csv")
    bt = read("benchmark_table.csv")
    bt = bt[(bt.split == "test") & bt.available.astype(bool)]
    md = ["# Router tables (generated by scripts/110_routers_markdown.py — do not edit by hand)", "",
          "Test split, η with the benchmark's exact tie expectation. **Bold** = paired 95% lower bound vs random "
          "above zero (unit bootstrap, 1000 draws). Gates are the 65-feature ridge/GBM of `benchmark_table.csv`.", ""]
    cells = list(dict.fromkeys(bt[bt.signal == "random"].cell))
    for q in (0.1, 0.2, 0.3, 0.5):
        md += [f"## η@{int(q * 100)}", "", "| cell | random | " + " | ".join(GATES + ROUTERS) + " |",
               "|" + "---|" * (len(GATES) + len(ROUTERS) + 2)]
        for cell in cells:
            row = [f"{bt[(bt.cell == cell) & (bt.signal == 'random') & np.isclose(bt.quota, q)].eta.iloc[0]:+.2f}"]
            for s in GATES:
                x = bt[(bt.cell == cell) & (bt.signal == s) & np.isclose(bt.quota, q)]
                row.append(fmt(x.iloc[0]) if len(x) else "—")
            for s in ROUTERS:
                x = rt[(rt.cell == cell) & (rt.signal == s) & np.isclose(rt.quota, q)]
                row.append(fmt(x.iloc[0]) if len(x) else "—")
            md.append(f"| {cell} | " + " | ".join(row) + " |")
        md.append("")
    md += ["## Cells where a signal beats random (paired lower bound > 0), by quota", "",
           "| signal | @10 | @20 | @30 | @50 | any quota (cells) |", "|---|---|---|---|---|---|"]
    both = pd.concat([bt[bt.signal.isin(GATES)], rt])
    for s in GATES + ROUTERS:
        x = both[(both.signal == s) & (both.minus_random_lo > 0)]
        md.append(f"| {s} | " + " | ".join(str(int((np.isclose(x.quota, q)).sum())) for q in (0.1, 0.2, 0.3, 0.5)) +
                  f" | {x.cell.nunique()} |")
    md.append("")

    r2 = sorted(glob.glob(str(ROOT / "results" / "raw" / "*_router_r2")))
    if r2:
        md += ["## R2 network", "", "| dataset | width multiplier | GFLOPs @128² | train frames | heads | TensorRT vs PyTorch Spearman (min over heads) |",
               "|---|---|---|---|---|---|"]
        for d in ("nuScenes", "KITTI"):
            f = Path(r2[-1]) / f"r2_{d}_meta.json"
            if f.exists():
                m = json.loads(f.read_text())
                rho = rt[(rt.signal == "R2_cnn_clf") & (rt.track == d)].trt_vs_torch_spearman.min()
                md.append(f"| {d} | {m['width_mult']} | {m['gflops']:.3f} | {m['train_frames']} | {len(m['heads'])} | {rho:.4f} |")
        md.append("")

    ovf = FINAL / "benchmark_budget_overheads_routers.json"
    if ovf.exists():
        ov = json.loads(ovf.read_text())["overheads"]
        keys = [k for k in ov if k.startswith(("r1_", "r2_", "gbm_batched", "gbm_predict", "ridge_predict", "cpu_mw"))]
        md += ["## Measured overheads (this board, single frame unless stated)", "", "| quantity | value |", "|---|---|"]
        md += [f"| `{k}` | {ov[k]:.4f} |" for k in keys if isinstance(ov[k], (int, float))]
        for t in ("nuScenes", "KITTI"):
            if t in ov:
                md.append(f"| `{t}.features_ms` (65-feature gate) | {ov[t]['features_ms']:.4f} |")
        md.append("")
    bf = FINAL / "benchmark_budget_routers.csv"
    if bf.exists():
        b = read("benchmark_budget_routers.csv")
        b = b[b.feasible.astype(bool) & b.signal.isin(BUDGET_SIGNALS)]
        for unit in ("ms", "mJ"):
            for lvl in (0.2, 0.5):
                x = b[(b.unit == unit) & np.isclose(b.budget_level, lvl)]
                md += [f"## Measured-cost allocation, {unit} budget at the {int(lvl * 100)}% level: η (escalated share)", "",
                       "| cell | " + " | ".join(BUDGET_SIGNALS) + " |", "|" + "---|" * (len(BUDGET_SIGNALS) + 1)]
                for cell in dict.fromkeys(x.cell):
                    row = []
                    for s in BUDGET_SIGNALS:
                        y = x[(x.cell == cell) & (x.signal == s)]
                        if not len(y):
                            row.append("—"); continue
                        y = y.iloc[0]
                        e = f"{y.eta:+.2f}"
                        if s != "random" and np.isfinite(y.minus_random_lo) and y.minus_random_lo > 0:
                            e = f"**{e}**"
                        row.append(f"{e} ({y.escalated_frac:.0%})")
                    md.append(f"| {cell} | " + " | ".join(row) + " |")
                md.append("")
    out = ROOT / "docs" / "routers_tables.md"
    out.write_text("\n".join(md))
    print("wrote", out)


if __name__ == "__main__":
    main()
