#!/usr/bin/env python
"""Task 5: render the real-perception nuPlan cells, reading and checks as docs/nuplan_real_perception_tables.md."""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FINAL = ROOT / "results" / "final"
PLANNERS = {"pdm_closed": "PDM-Closed", "idm": "IDM"}
LOSSES = ("safety", "scalar_J", "collision", "clearance_shortfall", "log_deviation")
VARIANT_NAMES = {"transported": "transported KITTI profile (Track B)", "primary": "real, primary (0.25/0.25, IoU 0.3, FP)",
                 "nofp": "real, no false positives", "s1": "real, S1 count-matched FULL threshold",
                 "iou50": "real, IoU 0.5"}


def pct(x):
    return "—" if not np.isfinite(x) else f"{100 * x:.1f}%"


def num(x, d=2):
    return "—" if not np.isfinite(x) else ("∞" if np.isinf(x) else f"{x:.{d}f}")


def ci(r, k, f):
    lo, hi = r[f"{k}_lo"], r[f"{k}_hi"]
    return f"{f(r[k])} [{f(lo)}, {f(hi)}]" if np.isfinite(lo) else f(r[k])


def cell_table(c, split, variants, losses):
    out = ["| planner | loss | variant | affected | V>0 / V<0 | harm rate [95% CI] | ρ [95% CI] | all-FULL reduction [CI] | oracle@20 reduction [CI] |",
           "|---|---|---|---|---|---|---|---|---|"]
    for p, pn in PLANNERS.items():
        for loss in losses:
            for v in variants:
                s = c[(c.planner == p) & (c.loss == loss) & (c.split == split) & (c.variant == v)]
                if s.empty:
                    continue
                r = s.iloc[0]
                out.append(f"| {pn} | {loss} | {v} | {int(r.affected)} / {int(r.states)} | {int(r.v_pos)} / {int(r.v_neg)} | "
                           f"{ci(r, 'harm_rate', pct)} | {ci(r, 'rho', num)} | {ci(r, 'all_full_reduction', pct)} | "
                           f"{ci(r, 'oracle20_reduction', pct)} |")
    return out


def main():
    c = pd.read_csv(FINAL / "nuplan_real_perception_cells.csv")
    ck = json.loads((FINAL / "nuplan_real_perception_checks.json").read_text())
    rec = pd.read_csv(FINAL / "nuplan_real_perception_recall.csv")
    md = ["# Real perception on the nuPlan external track — tables", "",
          "Generated by `scripts/117_nuplan_real_markdown.py` from `results/final/nuplan_real_perception_cells.csv`,",
          "`nuplan_real_perception_checks.json` and `nuplan_real_perception_recall.csv`. Pre-registration: RESEARCH_LOG.md,",
          "2026-09-14 14:44, with the ground-plane amendment. V = J(CHEAP) − J(FULL); harm rate = P(V<0 | V≠0);",
          "ρ = Σmax(−V,0)/Σmax(V,0); reductions are relative to all-CHEAP cost; CIs are log-level bootstrap, 1,000 draws.", "",
          "## Pre-registered reading (primary variant, all 1,440 states)", ""]
    rd = ck["reading_primary_all"]
    md += ["| aggregate | harm PDM-Closed | harm IDM | ρ PDM-Closed | ρ IDM | B-F1 fires (both < 5%) | both ≥ 20% and ρ ≥ 0.20 |",
           "|---|---|---|---|---|---|---|"]
    for agg in ("safety", "scalar_J"):
        a = rd[agg]
        md.append(f"| {agg} | {pct(a['harm_rate']['pdm_closed'])} | {pct(a['harm_rate']['idm'])} | "
                  f"{num(a['rho']['pdm_closed'])} | {num(a['rho']['idm'])} | {a['B-F1_fires']} | {a['harm_ge_20_and_rho_ge_20_both']} |")
    md += ["", f"**Reading: {rd['reading']}.**", "", "Same rule on the other variants and on the test split (not deciding):", "",
           "| variant | split | reading |", "|---|---|---|"]
    for k, v in ck["reading_other"].items():
        var, split = k.rsplit("_", 1)
        md.append(f"| {var} | {split} | {v['reading']} |")
    md += ["", "## Safety and scalar_J: transported profile vs real perception, all 34 logs", ""]
    md += cell_table(c, "all", ("transported", "primary"), ("safety", "scalar_J"))
    md += ["", "## The same on the 9 test logs", ""]
    md += cell_table(c, "test", ("transported", "primary"), ("safety", "scalar_J"))
    md += ["", "## Sensitivities (all 34 logs)", ""]
    md += cell_table(c, "all", ("nofp", "s1", "iou50"), ("safety", "scalar_J"))
    md += ["", "## Sensitivities (9 test logs)", ""]
    md += cell_table(c, "test", ("nofp", "s1", "iou50"), ("safety", "scalar_J"))
    md += ["", "## Components (all 34 logs)", ""]
    md += cell_table(c, "all", ("transported", "primary", "nofp", "s1", "iou50"), ("collision", "clearance_shortfall", "log_deviation"))
    md += ["", "## Recall of eligible in-camera tracks at the decision iterations (threshold 0.25)", "",
           "| class | distance | n | 320 IoU 0.3 | 640 IoU 0.3 | 320 IoU 0.5 | 640 IoU 0.5 | P(640 hit given 320 hit) | 320 hit, 640 miss | transported pred. 320 / 640 | KITTI 320 / 640 |",
           "|---|---|---|---|---|---|---|---|---|---|---|"]
    r0 = rec[~rec.min_height_10px]
    for _, r in r0[(r0.band_m == "all") | (r0.category == "all")].iterrows():
        md.append(f"| {r.category} | {r.band_m} | {int(r.n_nuplan)} | {r.recall_320_iou30:.3f} | {r.recall_640_iou30:.3f} | "
                  f"{r.recall_320_iou50:.3f} | {r.recall_640_iou50:.3f} | {r.p_640_given_320_iou30:.3f} | "
                  f"{100 * r.share_320_hit_640_miss_iou30:.1f}% | {r.transported_pred_320:.3f} / {r.transported_pred_640:.3f} | "
                  f"{r.kitti_recall_320:.3f} / {r.kitti_recall_640:.3f} |")
    md += ["", ck.get("recall_note", ""), "", "## Checks", ""]
    d, det, pr = ck["data"], ck["detection"], ck["projection"]
    md += [f"* **Data:** {d['images_verified']:,} images verified (CRC failures {d['crc_failures']}, decode failures "
           f"{d['decode_failures']}); image bytes {d['ledger']['member']['bytes']:,} in {d['ledger']['member']['requests']:,} "
           f"requests (cap 3.5 GB); metadata {d['ledger']['meta']['bytes']:,} B (cap 400 MB); every shard's logs equal its "
           f"File group: {d['all_shards_equal_file_group']}.",
           f"* **Detection:** 320 {det['ns_cheap_320']['ms_total_median']:.1f} ms, 640 {det['ns_full_640']['ms_total_median']:.1f} ms "
           f"median (decode {det['ns_cheap_320']['ms_decode_median']:.1f} ms); CPU+GPU "
           f"{det['energy']['ns_cheap_320']['cpu_gpu_mj_per_frame']:.1f} / {det['energy']['ns_full_640']['cpu_gpu_mj_per_frame']:.1f} mJ per frame; "
           f"S1 FULL threshold {det['s1_full_threshold']:.4f}.",
           f"* **Time alignment:** |Δt| median {pr['dt']['abs_ms_quantiles']['0.5']} ms, max {pr['dt']['abs_ms_quantiles']['1.0']} ms; "
           f"iterations over 50 ms: {pr['dt']['n_iterations_over_50ms']}.",
           f"* **Projection:** distortion monotone in every log: {pr['all_distortion_monotone']}; FP lift plane "
           f"{pr['fp_lift_ground_plane_train_val']['ground_z_ego_m']:.3f} m (camera {pr['fp_lift_ground_plane_train_val']['camera_height_above_ground_m']:.2f} m "
           f"above the road); lift on true vehicle boxes, median |range error| by band "
           + ", ".join(f"{k} {v:.2f} m" for k, v in pr["fp_lift_on_true_vehicle_boxes_decision_iterations"]["median_abs_range_error_by_band"].items()) + ".",
           f"* **Match IoU median:** 320 {pr['match_iou_quantiles']['cheap_025_iou30']['0.5']}, 640 {pr['match_iou_quantiles']['full_025_iou30']['0.5']}."]
    for p, pn in PLANNERS.items():
        r = ck.get(f"reference_{p}")
        if r:
            md.append(f"* **{pn} reference and identity:** reference reproduces Track B on all {r['states']} states: "
                      f"{r['reference_reproduces_trackb']} (mismatches {r['reference_vs_trackb_mismatches']}); identity observation equal "
                      f"on {r['identity_observation_equal_states']} states, planner outputs equal on {r['identity_planned_states']} planned "
                      f"states (mismatches {r['identity_planner_mismatches']}): {r['identity_reproduces_reference']}.")
    bd = ck.get("branch_descriptives_per_state", {})
    if bd:
        md += ["", "Per decision state: " + ", ".join(f"{k} {v}" for k, v in bd.items() if k.startswith(("n_", "kept_", "fp_"))) + "."]
    (ROOT / "docs" / "nuplan_real_perception_tables.md").write_text("\n".join(md) + "\n")
    print("wrote docs/nuplan_real_perception_tables.md")


if __name__ == "__main__":
    main()
