#!/bin/bash
# Supplementary IDM route-fix rerun (research log amendment, 2026-09-15): supervise_idm_fix.sh ran 93 only with
# --routers, so the primary and _1thread two-level budget tables still held pre-fix IDM rows.
# Strictly one heavy job at a time; stops at the first failure or failed check.  Do not edit this file while it runs.
cd /home/kongwoang/research/risk-aware-perception
LOG=logs/supervise_idm_fix2.log
A=results/archive/pre_idm_route_fix/final
say () { echo "[$(date +%H:%M:%S)] $*" | tee -a $LOG; }
fan () { curl -s -X POST -H 'content-type: application/json' -d "$1" localhost:8765/api/jetson/fan > /dev/null; }
gate () { while [ -n "$(./scripts/busy.sh)" ]; do sleep 30; done; sync; sleep 5; }
step () { local l="$1"; shift; gate; say "$l start"; "$@" >> logs/idmfix2_$l.log 2>&1; local rc=$?; say "$l exit $rc"; return $rc; }
quit () { fan '{"mode":"auto","profile":"quiet"}'; say "STOPPED: $1"; exit 1; }

fan '{"mode":"manual","pwm":255}'
say "IDM route-fix supplementary chain start"
step b93 scripts/py scripts/93_budget_allocation.py --reuse_overheads $A/benchmark_budget_overheads.json || quit "93 primary failed"
step b93_1thread env OMP_NUM_THREADS=1 scripts/py scripts/93_budget_allocation.py --tag benchmark_budget_1thread \
     --suffix _1thread --reuse_overheads $A/benchmark_budget_overheads_1thread.json || quit "93 _1thread failed"
step b94 scripts/py scripts/94_benchmark_markdown.py || quit "94 failed"
step compare scripts/py scripts/121_idm_route_fix_checks.py --stage compare || quit "comparison: rows that should not change moved"
fan '{"mode":"auto","profile":"quiet"}'
say "IDM FIX SUPPLEMENTARY CHAIN DONE"
