#!/bin/bash
# IDM route-fix rerun (research log, 2026-09-15): every result that depends on IDM, strictly one heavy job at a time.
# Stops at the first failure or failed check.  Do not edit this file while it runs.
cd /home/kongwoang/research/risk-aware-perception
LOG=logs/supervise_idm_fix.log
say () { echo "[$(date +%H:%M:%S)] $*" | tee -a $LOG; }
fan () { curl -s -X POST -H 'content-type: application/json' -d "$1" localhost:8765/api/jetson/fan > /dev/null; }
gate () { while [ -n "$(./scripts/busy.sh)" ]; do sleep 30; done; sync; sleep 5; }
step () { local l="$1"; shift; gate; say "$l start"; "$@" >> logs/idmfix_$l.log 2>&1; local rc=$?; say "$l exit $rc"; return $rc; }
quit () { fan '{"mode":"auto","profile":"quiet"}'; say "STOPPED: $1"; exit 1; }

fan '{"mode":"manual","pwm":255}'
say "IDM route-fix chain start"
step trackb_idm scripts/pynuplan scripts/82_nuplan_counterfactual.py --planner idm --scenarios 60 --per_scenario 24 || quit "Track B IDM run failed"
step check_trackb scripts/py scripts/121_idm_route_fix_checks.py --stage trackb || quit "IDM reference sanity check failed"
step x83 scripts/py scripts/83_external_transfer.py --nboot 400 || quit "83 failed"
step x85 scripts/py scripts/85_external_2x2.py || quit "85 failed"
step b92 scripts/py scripts/92_benchmark_table.py || quit "92 failed"
step b94 scripts/py scripts/94_benchmark_markdown.py || quit "94 failed"
step r103 scripts/py scripts/103_routers_r1.py || quit "103 failed"
step b93 scripts/py scripts/93_budget_allocation.py --routers --tag benchmark_budget_routers \
     --reuse_overheads results/archive/pre_idm_route_fix/final/benchmark_budget_overheads_routers.json || quit "93 failed"
step r110 scripts/py scripts/110_routers_markdown.py || quit "110 failed"
step t5_ref scripts/pynuplan scripts/115_nuplan_real_counterfactual.py --planner idm --phase ref || quit "Task 5 IDM reference/identity check failed"
step t5_branches scripts/pynuplan scripts/115_nuplan_real_counterfactual.py --planner idm --phase branches || quit "Task 5 IDM branches failed"
step t5_checks scripts/py scripts/116_nuplan_real_cells.py --stage checks || quit "116 checks failed"
step t5_cells scripts/py scripts/116_nuplan_real_cells.py --stage cells || quit "116 cells failed"
step t5_md scripts/py scripts/117_nuplan_real_markdown.py || quit "117 failed"
step t7 scripts/py scripts/120_nuplan_real_allocation.py || quit "120 failed"
step fig118 scripts/py scripts/118_figure_exports.py || quit "118 failed"
step compare scripts/py scripts/121_idm_route_fix_checks.py --stage compare || quit "comparison: rows that should not change moved"
fan '{"mode":"auto","profile":"quiet"}'
say "IDM FIX CHAIN DONE"
